[package]
name = "rhizome-resin-wfc"
version = "0.1.0"
edition = "2024"
description = "Wave Function Collapse algorithm"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rhizome-lab/resin"

[dependencies]
