[package]
name = "rhizome-resin-expr"
version = "0.1.0"
edition = "2024"
description = "Expression language parser for resin"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rhizome-labs/resin"

[dependencies]
