[package]
name = "rhizome-resin-scatter"
version = "0.1.0"
edition = "2024"
description = "Point scattering and instancing"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rhizome-lab/resin"

[dependencies]
glam.workspace = true
