[package]
name = "rhizome-resin-fluid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Fluid simulation for resin"

[dependencies]
glam = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
