[package]
name = "extract-ops"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
syn = { version = "2", features = ["full", "parsing"] }
quote = "1"
walkdir = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
