[package]
name = "unshape-geometry"
version = "0.1.0"
edition = "2024"
description = "Core types and traits for unshape"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rhizome-lab/resin"

[dependencies]
glam.workspace = true
