[package]
name = "rhizome-resin-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core types and traits for resin"

[dependencies]
glam.workspace = true
thiserror.workspace = true
rhizome-resin-macros = { path = "../resin-macros" }
