[package]
name = "rhizome-resin-lsystem"
version = "0.1.0"
edition = "2024"
description = "L-systems for procedural generation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rhizome-lab/resin"

[dependencies]
glam.workspace = true
