[package]
name = "resin-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Audio synthesis for resin"

[dependencies]
resin-core = { path = "../resin-core" }
