[package]
name = "unshape-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core types and traits for unshape (CPU, GPU, etc.)"

[features]
default = []

[dependencies]
unshape-core = { path = "../unshape-core" }
thiserror.workspace = true
