[package]
name = "rhizome-resin-mesh"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "3D mesh generation for resin"

[dependencies]
glam.workspace = true
ordered-float.workspace = true
rhizome-resin-core = { path = "../resin-core" }
