[package]
name = "rhizome-resin-automata"
version = "0.1.0"
edition = "2024"
description = "Cellular automata (1D elementary, 2D Game of Life, etc.)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rhizome-lab/resin"

[dependencies]
