[package]
name = "unshape-lsystem"
version = "0.1.0"
edition = "2024"
description = "L-systems for procedural generation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rhizome-lab/resin"

[features]
default = []
serde = ["dep:serde"]
dynop = ["dep:unshape-op", "dep:serde_json", "serde"]

[dependencies]
glam.workspace = true
serde = { workspace = true, optional = true }
unshape-op = { path = "../unshape-op", optional = true }
serde_json = { version = "1", optional = true }
